replicaCount: 1

image:
  repository: registry.minter.network/minter-network-web
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: registry.minter.network

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80
  
deployment:
  healthCheckPath: /cmc/cryptocurrency/listings/latest
#  healthCheckPath: /coinsblack/exportxml.xml

ingress:
  domain: ""
  tlsname: ""
  #issuer: letsencrypt-http
  clusterissuer: letsencrypt-prod

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
