apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # production
    {{- if .Values.ingress.clusterissuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterissuer }}
    {{- end }}
    # staging
    {{- if .Values.ingress.issuer }}
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
    {{- end }}
spec:
  rules:
    - host: "www.{{ .Values.ingress.domain }}"
      http:
        paths:
          - backend:
              serviceName: "{{ include "chart.fullname" . }}"
              servicePort: {{ .Values.service.port }}
            path: /
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
        - "www.{{ .Values.ingress.domain }}"
      secretName: {{ .Values.ingress.tlsname }}
